### ISSUE TITLE
Configuration file for the Multisense-SL

### ISSUE THREAD

**Issue by dkanou** [ADVRHumanoids/XBotCore#1]
We tried the following:
-- roscore in the control PC
-- multisense in the vision PC (ROS master url has been configured to be seeing in the control PC)

We started and homed the robot and tried to check if the whole TF including the Multisense-SL is visible in the control or pilot PC, which is not the case.  Not sure if there is something in the config file that need to be touched or the ROS urls are not correct!

**Comment by liesrock** [comment]
Hi @dkanou : this should be in WALKMAN status repo. I just did it for you, let's continue there.
