### ISSUE TITLE
Dealing with NED IMU orientation

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/XBotCore#10]
Recently we found out with Luca that our IMU will provide the orientation of its own sensor frame (as depicted on the sensor itself) w.r.t. a world frame according to the NED (north-east-down) convention. Since we work with a world with +Z pointing upwards, we need to take care of this fact appropriately.

My suggestion is to compensate for such a difference by pre-applying a rotation of +180 degrees about the X axis when reading from the sensor (only for what concerns the orientation), i.e. at the `XBotEcat` layer.

This is equivalent to using the following code for reading the IMU orientation:
```
quaternion[0] = actual_pdo_rx_imu.w_quat;
quaternion[1] = -actual_pdo_rx_imu.z_quat;
quaternion[2] = actual_pdo_rx_imu.y_quat;
quaternion[3] = -actual_pdo_rx_imu.x_quat;
```

I pushed thus change to a branch of `XBotEcat`.

@nkashiri  @ntsagarakis  @liesrock  @EnricoMingo  @pepperig

**Comment by liesrock** [comment]
We currently use the IMU with @alaurenzi modification.

**Comment by alaurenzi** [comment]
I reopen since if I remember correctly that one is just a local change on centauro embedded.. not really a solution!

**Comment by liesrock** [comment]
Ok, thanks.
The issues can't be here forever: I ask the others mentioned to give us their opinion ASAP and to find a real solution.

@nkashiri @ntsagarakis @liesrock @EnricoMingo @pepperig

**Comment by liesrock** [comment]
Ok, we take this as the final solution to solve the above described issue: I will merge in this https://github.com/ADVRHumanoids/XBotEcat/pull/1

@ADVRHumanoids/advr-developers
