### ISSUE TITLE
wheels not controlled on the centauro-pilot pc

### ISSUE THREAD

**Issue by mkamedula** [ADVRHumanoids/XBotCore#12]
run:
        roslaunch centauro_gazebo centauro_world.launch paused:=false 
wheels are not controlled by xbotcore

**Comment by liesrock** [comment]
XBotCore works with config file, as very detailed described in the [XBotCore wiki](https://github.com/ADVRHumanoids/XBotCore/wiki/quick-start).

I noticed you were using a config file with no_wheels.

Double check it and try to read more carefully the wiki: I put back the centauro_simple_example.yaml as config file in the system.
