### ISSUE TITLE
Not RT synchronous/asynchronous robot API

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XBotCore#15]
The idea is to have an api that allows to have the following behavior
- specify the type of trajectory (ptp, linear, ecc)
- specify the cartesian coordinates of the target
- synchronous move call that wait for the robot reaching the target position
- asynchronous move call that notify the user when the robot reach the target position

This would be useful in case we want implement a teaching like programming.

**Comment by alaurenzi** [comment]
Have a look to [**this**](https://github.com/ADVRHumanoids/CartesianInterface) :sunglasses:

**Comment by pepperig** [comment]
Yes! ;-)
