### ISSUE TITLE
Config files and XBotCore

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/XBotCore#2]
It would be nice to improve the config file management w.r.t. XBotCore
 1) the final part of config files (xbotcore-related) should be moved to a separate config?
 2) the urdf/srdf/jointmap used by XBotCore should be taken relative to $ROBOTOLOGY_ROOT

**Comment by pepperig** [comment]
I agree. We can have a file just with the things that matter to the end user. Moreover in the future we could develop a GUI that deals with all those setting...For example in the case of plugins the user could just see a list of plugins and drag and drop the one he needs

**Comment by liesrock** [comment]
As described in https://github.com/ADVRHumanoids/XCM/issues/32.
