### ISSUE TITLE
Build error due to wrong name in package.xml

### ISSUE THREAD

**Issue by DaniloCaporale** [ADVRHumanoids/XBotCore#20]
Hi,

tried to push this fix but it's locked.

In package.xml had to replace the following to build.

< name >XCM< /name >
< name >XBotCore< /name >

Cheers,

Danilo

**Comment by liesrock** [comment]
@pepperig did you had this issue? I did not.

**Comment by pepperig** [comment]
nope

**Comment by liesrock** [comment]
@DaniloCaporale can you please give us some more details about the error?
