### ISSUE TITLE
Adding the possibility to SCP log

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/XBotCore#22]
As title

**Comment by liesrock** [comment]
@alaurenzi note for the logger the changes are here: bf44e2bf910430c70388a9fe8e5ebd57cf6ac022

**Comment by liesrock** [comment]
@alaurenzi can you give me a feedback here or in the related pull request?

**Comment by alaurenzi** [comment]
For some reason was not working on my latest experiments on centauro

**Comment by liesrock** [comment]
I tried with different plugins, but simple ones looks working: I wil try with a complex one (chengxu_walking) on walkman.

**Comment by liesrock** [comment]
Also in simulation, with the dummy it works with different plugins and different robots.

**Comment by liesrock** [comment]
Integrated in https://github.com/ADVRHumanoids/XBotCore/commit/5b57a239b772d0a42a469e8759b43d5d1f14f82d
