### ISSUE TITLE
Check behavior of rosutils from real time

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XBotCore#26]
I experienced some issue using the kuka robot. I will check the log to get more info but it could be related to increasing of the control period (kuka has hard time constraint).

**Comment by liesrock** [comment]
Any other info in this?

**Comment by pepperig** [comment]
I tried again with KUKA robot and it look working fine. However now we have a separate R-HAL thread.
I do not know if there are slowdowns in the control loop when using this feature.

**Comment by liesrock** [comment]
I believe we did not noticed this behavior ever on our humanoids: if @alaurenzi can confirm I close.

**Comment by alaurenzi** [comment]
There should be no slowdowns from my point of view
