### ISSUE TITLE
Separate thread for HAL

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XBotCore#27]
RT thread for the robot which communicate with the XBot thread using shared memory with mutex or using IDDP.
This will allow to have an high frequency robot control loop.

**Comment by alaurenzi** [comment]
But what exactly is the purpose?
The actual feedback loops are two:
- the first is closed on the DSPs
- the second is closed on the embedded pc and directly involves the RT plugins

How would a separate very fast, communication thread help performance if the RT plugins are slower?

**Comment by pepperig** [comment]
solved in #37
