### ISSUE TITLE
Issue switch RT-NRT web 

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XBotCore#30]
This issue was solved but somehow we removed the followig code
``
 /* Receive commands from the master communication handler,
     * i.e. the only one enabled to send commands to the robot */
    if(_master_communication_ifc->getPluginStatus(_plugin_names[xbot_communication_idx]) == "STOPPED"){
        _master_communication_ifc->resetReference();
    }
    else{
        _master_communication_ifc->receiveReference(); // this updates robot
}
``
Why did we do that?

**Comment by alaurenzi** [comment]
This was done in which commit?

**Comment by pepperig** [comment]
done in ecc15c7121a4915d63673e0402bfdb4b93bfcffa
@liesrock @alaurenzi
