### ISSUE TITLE
Shared memory issue with std::any

### ISSUE THREAD

**Issue by pepperig** [ADVRHumanoids/XBotCore#5]
@alaurenzi I am creating this issue so we do not forget. 
We have a SEGFAULT on closing phase when we use the shared memory. The problem in on the destructor of the std::any(). NOTE that std::any allocate the shared_ptr on the heap.

**Comment by alaurenzi** [comment]
Before starting with a possible refactor of the `SharedMemory` (which anyway will have to be done to make it thread-safe), I would like to make sure that putting shared pointers inside a `boost::any` is actually causing problems. Can you verify this with a small self-contained example?

**Comment by pepperig** [comment]
When possible I can try. However in debug mode you can see the error.

**Comment by alaurenzi** [comment]
Refactored in 0f6b35872dbdefcc4d30ba8, apparently the closing is now ok

**Comment by liesrock** [comment]
Great, I close it.
