### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by williamalexmoran** [ADVRHumanoids/XBotCore#54]
We are trying to install XBotCore for use with a humanoid robot. We followed the installation instructions for advr-superbuild and are having some issues. Every subdirectory we set to "ON" returns "Package not found. Will be downloaded and built", and when we look through the folders they are all empty. As an alternative, we also tried to clone this repository directly, but neither method found "generate_XBot_Plugin.sh". We are stuck on this step, any suggestions on how to move forward? Thanks.

**Comment by pepperig** [comment]
Try to update the superbuild, then delete the build folder and try again.
Do not forget to source the terminal at the end.

**Comment by pepperig** [comment]
Also this type of issue should be opened here https://github.com/ADVRHumanoids/advr-superbuild/issues

**Comment by liesrock** [comment]
continuing on https://github.com/ADVRHumanoids/advr-superbuild/issues
